port: 4000
host: 0.0.0.0
safe: false

# Site settings
title: Bobgoo - Apps made with ❤️ in Barcelona
description: We think, design, develop and publish successful apps. Since 2011 turning business ideas into reality. 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

url: https://www.bobgoo.com
enforce_ssl: www.bobgoo.com


# User settings
username: Bobgoo, S.L.
email_username: hi@bobgoo.com
twitter_username: bobgoolabs

# Google-analytics
google_analytics_key: UA-25289053-4

# Opengraph
opengraph:
    title: 
    description:
    image: /assets/img/FBBanner.png
    height: 630
    width: 1200

# Favicons
favicon:     /assets/favicon/favicon.ico
touch_icon:  /assets/faviconapple-touch-icon.png

exclude: ['package.json', 'src' , 'node_modules']
